import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        <header className="bg-white shadow-md">
          <nav className="container mx-auto flex items-center justify-between p-4">
            <h1 className="text-xl font-bold text-blue-600">Todo List App</h1>
            <div className="flex gap-4">
              <Link
                href="/TodoLists/TodoWriteForm"
                className="px-4 py-2 rounded-md hover:bg-blue-100 text-blue-600 font-medium transition"
              >
                글쓰기
              </Link>
              <Link
                href="/TodoLists/TodoList"
                className="px-4 py-2 rounded-md hover:bg-blue-100 text-blue-600 font-medium transition"
              >
                글 목록
              </Link>
            </div>
          </nav>
        </header>
        <main className="container mx-auto flex-1 p-6">{children}</main>
        <footer className="bg-white shadow-inner text-center py-4 text-gray-500 text-sm">
          © 2025 Todo List App. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
